### ISSUE TITLE
The mappning of bank assigned creditor identifier [UBL]

### ISSUE THREAD

**Issue by SLennartsson** [ConnectingEurope/eInvoicing-EN16931#104]
BT-90, Bank assigned creditor identifier, has cardinality 0..1 in the EN. Through the syntax binding to UBL, BT-90 may be mapped to 
•	Either AccountingSupplierParty/Party/PartyIdentification>/ID with schemeID=”SEPA”
•	Or Payee/PartyIdentification>/ID with schemeID=”SEPA”.

There is no validation rule to block that bank assigned creditor identifiers are given in both places at the same time.

The following excerpt generates no validation signal at all:
```xml
…
	<cac:AccountingSupplierParty>
		<cac:Party>
			<cbc:EndpointID schemeID="0007">1234567890</cbc:EndpointID>
			<cac:PartyIdentification>
				<cbc:ID schemeID="SEPA">111333555777</cbc:ID >
			</cac:PartyIdentification>
…
	<cac:PayeeParty>
		<cac:PartyIdentification>
			<cbc:ID schemeID="SEPA">2224446660</cbc:ID >
		</cac:PartyIdentification>
		<cac:PartyName>
			<cbc:Name>Finansiell Support u.p.a.</cbc:Name>
		</cac:PartyName>
		<cac:PartyLegalEntity>
			<cbc:CompanyID schemeID="0007">5566778899</cbc:CompanyID>
		</cac:PartyLegalEntity>
	</cac:PayeeParty>
…
```

Request: Introduce a fatal validation rule to be triggered is more than one bank assigned creditor identifier is encountered in the document.

**Comment by oriol** [comment]
Solved in UBL-SR-29 firing the rule as fatal.

**Comment by sarafacchinettiIC** [comment]
I believe this was solved by UBL-SR-41 (as mentioned in https://github.com/CenPC434/validation/issues/92 )

**Comment by sarafacchinettiIC** [comment]
But I still have a doubt on this.
Is this correct when BT-90 refers to the Payee?

 
    <cac:PayeeParty>
		<cac:PartyIdentification>
		  <cbc:ID schemeID="0180" >Payee identifier </cbc:ID>
		</cac:PartyIdentification>
		
		<cac:PartyIdentification>
		 <cbc:ID schemeID="SEPA">Bank account identifier referring to the payee </cbc:ID> 
	    </cac:PartyIdentification>

**Comment by sarafacchinettiIC** [comment]
Why not using for mapping the BT-90 the `/Invoice/cac:PaymentMeans/cac:PaymentMandate/cac:PayeeFinancialAccount/cbc:ID?`

**Comment by sarafacchinettiIC** [comment]
I'll open a new issue with relation to ubl BT-90 mapping
